# Generated by Django 3.2.3 on 2021-06-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=256)),
                ('start', models.TimeField()),
                ('end', models.TimeField(null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Music',
            },
        ),
        migrations.CreateModel(
            name='PartFormat',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('part_data', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=32)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamica_app.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamica_app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='part_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamica_app.partformat'),
        ),
    ]
