# Generated by Django 3.2.3 on 2021-06-17 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamica_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 17, 15, 0)),
            preserve_default=False,
        ),
    ]
