# Generated by Django 3.2.3 on 2021-06-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamica_app', '0002_event_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Nowhere', max_length=256),
        ),
    ]
