# Generated by Django 3.2.3 on 2021-06-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamica_app', '0002_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
