# Generated by Django 3.2.3 on 2021-06-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamica_app', '0003_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=256),
        ),
    ]
