# Generated by Django 3.2.3 on 2021-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamica_app', '0003_request_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instrument',
            field=models.CharField(choices=[(1, 'Trumpet'), (2, 'Trombone'), (3, 'Euphonium'), (4, 'French Horn'), (5, 'Tenor Horn'), (6, 'Tuba')], default='Trumpet', max_length=32),
            preserve_default=False,
        ),
    ]
