# Generated by Django 3.2.3 on 2021-07-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamica_app', '0004_userprofile_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_password',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instrument',
            field=models.CharField(choices=[('Trumpet', 'Trumpet'), ('Trombone', 'Trombone'), ('Euphonium', 'Euphonium'), ('French Horn', 'French Horn'), ('Tenor Horn', 'Tenor Horn'), ('Tuba', 'Tuba')], max_length=32),
        ),
    ]
